<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net48</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.ExpressApp.Security.Xpo" Version="25.1.4" />
    <PackageReference Include="DevExpress.Persistent.BaseImpl.Xpo" Version="25.1.4" />
  
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Employees.xml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BusinessObjectsLibrary\BusinessObjectsLibrary.csproj" />
  </ItemGroup>
</Project>