<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Models\Base\**" />
    <Compile Remove="Models\EFCore\Entities\General\**" />
    <Compile Remove="Models\XPO\General\**" />
    <Compile Remove="Models\XPO\PermissionPolicy\**" />
    <EmbeddedResource Remove="Models\Base\**" />
    <EmbeddedResource Remove="Models\EFCore\Entities\General\**" />
    <EmbeddedResource Remove="Models\XPO\General\**" />
    <EmbeddedResource Remove="Models\XPO\PermissionPolicy\**" />
    <None Remove="Models\Base\**" />
    <None Remove="Models\EFCore\Entities\General\**" />
    <None Remove="Models\XPO\General\**" />
    <None Remove="Models\XPO\PermissionPolicy\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Models\Base\AddressImpl.cs" />
    <Compile Include="Models\Base\IAddress.cs" />
    <Compile Include="Models\Base\IContact.cs" />
    <Compile Include="Models\Base\ICountry.cs" />
    <Compile Include="Models\Base\ICustomPermissionPolicyUser.cs" />
    <Compile Include="Models\Base\IDemoTask.cs" />
    <Compile Include="Models\Base\IDepartment.cs" />
    <Compile Include="Models\Base\Enums\Priority.cs" />
    <Compile Include="Models\Base\Enums\TitleOfCourtesy.cs" />
    <Compile Include="Models\Base\IPerson.cs" />
    <Compile Include="Models\Base\IPhoneNumber.cs" />
    <Compile Include="Models\Base\IPosition.cs" />
    <Compile Include="Models\Base\ITask.cs" />
    <Compile Include="Models\Base\PersonImpl.cs" />
    <Compile Include="Models\Base\PhoneNumberImpl.cs" />
    <Compile Include="Models\Base\TaskImpl.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="10.*" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.2" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="5.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="5.0.0" />

    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.*">
      <PrivateAssets>none</PrivateAssets>
      <IncludeAssets>all</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.Persistent.BaseImpl.EFCore" Version="25.2.5-pre-26040" />
    <PackageReference Include="DevExpress.ExpressApp.EFCore" Version="25.2.5-pre-26040" />
    <PackageReference Include="DevExpress.ExpressApp.Security.Xpo" Version="25.2.5-pre-26040" />
    <PackageReference Include="DevExpress.Persistent.BaseImpl.Xpo" Version="25.2.5-pre-26040" />
  </ItemGroup>
</Project>
