'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace WebFormsApplication


    Partial Public Class _Default

        ''' <summary>
        ''' LogoutButton control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected LogoutButton As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' EmployeeGrid control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected EmployeeGrid As Global.DevExpress.Web.ASPxGridView

        ''' <summary>
        ''' EmployeeDataSource control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected EmployeeDataSource As Global.DevExpress.Xpo.XpoDataSource

        ''' <summary>
        ''' DepartmentDataSource control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected DepartmentDataSource As Global.DevExpress.Xpo.XpoDataSource
    End Class
End Namespace
