'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace WebFormsApplication


    Partial Public Class LoginForm

        ''' <summary>
        ''' UserNameBox control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected UserNameBox As Global.DevExpress.Web.ASPxTextBox

        ''' <summary>
        ''' PasswordBox control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected PasswordBox As Global.DevExpress.Web.ASPxTextBox

        ''' <summary>
        ''' LoginButton control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected LoginButton As Global.DevExpress.Web.ASPxButton
    End Class
End Namespace
